plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.halot455.wuchangwallpaper'
    compileSdk 35

    defaultConfig {
        applicationId 'com.halot455.wuchangwallpaper'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '3.0-interactive-kotlin'
    }

    buildTypes {
        release { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
}
